/**
 * finance.config.js - Modular Config for CRC / TeraX v2
 * Domain: finance
 */
(function() {
  window.__MODULE_CONFIGS__ = window.__MODULE_CONFIGS__ || {};
  Object.assign(window.__MODULE_CONFIGS__, {
  mtr: {
    label: 'MTR Transactions',
    subtitle: 'Manage internal money transfers',
    endpoint: '/table/mtr',
    pk: 'transaction_id',
    icon: '💹',
    groupBy: ['company_id', 'transaction_type', 'currency'],
    columns: [
      { key: 'transaction_id', label: 'ID', hidden: true },
      { key: 'account', label: 'Account', optionsFrom: 'account', optionValue: 'account_id', optionLabel: 'account_name' },
      { key: 'company_id', label: 'My Company', labelKey: 'col.my_company' },
      { key: 'transaction_type', label: 'Type' },
      { key: 'amount', label: 'Amount' },
      { key: 'currency', label: 'Currency' },
      { key: 'exchange_rate', label: 'Exchange Rate' },
      { key: 'amount_in_base_currency', label: 'Amount in Base Currency', type: 'number' },
      { key: 'transaction_date', label: 'Date' },
    ],
    fields: [
      { key: 'request', label: 'Request ID', type: 'select', optionsFrom: 'request', optionValue: 'request_id', optionLabel: 'description', hidden: true },
      { key: 'account', label: 'Account ID', type: 'select', optionsFrom: 'account', optionValue: 'account_id', optionLabel: 'account_name', hidden: true },
      { key: 'transaction_type', label: 'Type', type: 'segmented', options: ['Incoming', 'Outgoing'], defaultValue: 'Incoming', required: true },
      { key: 'currency', label: 'Currency', type: 'select', optionsFrom: 'account_currency', optionValue: 'code', optionLabel: 'label' },
      { key: 'exchange_rate', label: 'Exchange Rate', type: 'text', defaultValue: '1', required: true },
      { key: 'amount', label: 'Amount', type: 'text', required: true },
      { key: 'amount_in_base_currency', label: 'Amount in Base Currency', type: 'text', createReadonly: true, editReadonly: true },
      { key: 'description', label: 'Description', type: 'textarea', full: true, required: true },
      { key: 'note', label: 'Note', type: 'textarea', full: true },
      { key: 'status', label: 'Status', type: 'text', hidden: true, defaultValue: 55 },
      { key: 'transaction_date', label: 'Transaction Date', type: 'date', required: true },
    ],
    detailFields: [
      { section: 'transaction information' },
      { key: 'transaction_id', label: 'ID' },
      { key: 'transaction_type', label: 'Type' },
      { key: 'transaction_date', label: 'Date' },
      { key: 'account', label: 'Account', optionsFrom: 'account', optionValue: 'account_id', optionLabel: 'account_name' },
      { key: 'currency', label: 'Currency' },
      { key: 'exchange_rate', label: 'Exchange Rate' },
      { key: 'amount', label: 'Amount' },
      { key: 'amount_in_base_currency', label: 'Amount in Base Currency', type: 'number' },
      { key: 'description', label: 'Description', full: true },
      { key: 'note', label: 'Note', full: true },
      { key: 'request', label: 'Request', optionsFrom: 'request', optionValue: 'request_id', optionLabel: 'description' },
    ],
    displayName: (r) => r.description || r.transaction_id,
  },

  account: {
    label: 'Account',
    subtitle: 'Manage financial accounts',
    endpoint: '/table/account',
    pk: 'account_id',
    icon: '🏦',
    groupBy: ['company_entity', 'account_status', 'type', 'currency'],
    columns: [
      { key: 'account_id', label: 'ID', hidden: true },
      { key: 'account_name', label: 'Account Name' },
      { key: 'type', label: 'Type' },
      { key: 'balance', label: 'Balance', labelKey: 'col.balance', type: 'number' },
      { key: 'currency', label: 'Currency' },
      { key: 'exchange_rate', label: 'Exchange Rate' },
      { key: 'balance_in_base_currency', label: 'Balance in Base Currency', labelKey: 'col.balance_in_base_currency', type: 'number' },
      { key: 'account_infor', label: 'Account Info' },
      { key: 'account_status', label: 'Status', badge: true },
      { key: 'bank_name', label: 'Bank Name' },
      { key: 'account_number', label: 'Account No.' },
      { key: 'transaction_managed_by', label: 'Transaction Managed By', optionsFrom: 'employee', optionValue: 'employee_id', optionLabel: 'full_name' },
      { key: 'finance_control', label: 'Finance Control', optionsFrom: 'employee', optionValue: 'employee_id', optionLabel: 'full_name' },
      { key: 'id_request', label: 'Request ID' },
      { key: 'company_entity', label: 'My Company', labelKey: 'col.my_company', optionsFrom: 'my_company', optionValue: 'my_company_id', optionLabel: 'company_shortname', hidden: true }
    ],
    fields: [
      { section: 'account summary' },
      { key: 'company_entity', label: 'MY COMPANY', labelKey: 'col.my_company', type: 'select', optionsFrom: 'my_company', optionValue: 'my_company_id', optionLabel: 'company_shortname', createReadonly: true, editReadonly: true },
      { key: 'account_name', label: 'ACCOUNT NAME', type: 'text', required: true },
      { key: 'account_number', label: 'ACCOUNT NUMBER', type: 'text' },
      { key: 'bank_name', label: 'BANK NAME', type: 'text' },
      { key: 'account_label', label: 'ACCOUNT LABEL', type: 'text', createReadonly: true, editReadonly: true, virtual: true, full: true },
      { key: 'type', label: 'TYPE', type: 'segmented', options: ['Bank', 'Cash', 'Other'], required: true },
      { key: 'account_status', label: 'ACCOUNT STATUS', type: 'segmented', options: [{ value: 19, label: 'Open' }, { value: 20, label: 'Closed' }], defaultValue: 19 },
      { section: 'financial information' },
      { key: 'currency', label: 'CURRENCY', type: 'select', optionsFrom: 'cms_currency', optionValue: 'code', optionLabel: 'label', required: true },
      { key: 'exchange_rate', label: 'EXCHANGE RATE', type: 'text', required: true },
      { section: 'management & control' },
      { key: 'transaction_managed_by', label: 'TRANSACTION MANAGED BY', type: 'multiselect', optionsFrom: 'employee', optionValue: 'employee_id', optionLabel: 'full_name', full: true, required: true },
      { key: 'finance_control', label: 'FINANCE CONTROL', type: 'multiselect', optionsFrom: 'employee', optionValue: 'employee_id', optionLabel: 'full_name', full: true },
      { section: 'additional information' },
      { key: 'id_request', label: 'REQUEST ID', type: 'text', hidden: true },
      { key: 'account_infor', label: 'ACCOUNT INFOR', type: 'textarea', full: true }
    ],
    detailFields: [
      { section: 'account' },
      { key: 'company_entity', label: 'MY COMPANY', labelKey: 'col.my_company' },
      { key: 'account_name', label: 'ACCOUNT NAME' },
      { key: 'latest_transaction_date', label: 'LATEST TRANSACTION' },
      { key: 'type', label: 'TYPE' },
      { key: 'account_number', label: 'ACCOUNT NUMBER' },
      { key: 'bank_name', label: 'BANK NAME' },
      { section: 'financial information' },
      { key: 'currency', label: 'CURRENCY' },
      { key: 'exchange_rate', label: 'EXCHANGE RATE' },
      { key: 'balance', label: 'BALANCE', labelKey: 'col.balance' },
      { key: 'balance_in_base_currency', label: 'BALANCE IN BASE CURRENCY', labelKey: 'col.balance_in_base_currency' },
      { section: 'management & control' },
      { key: 'transaction_managed_by', label: 'TRANSACTION MANAGED BY', optionsFrom: 'employee', optionValue: 'employee_id', optionLabel: 'full_name' },
      { key: 'finance_control', label: 'FINANCE CONTROL', optionsFrom: 'employee', optionValue: 'employee_id', optionLabel: 'full_name' },
      { section: 'additional information' },
      { key: 'id_request', label: 'REQUEST ID' },
      { key: 'request', label: 'REQUEST', optionsFrom: 'request', optionValue: 'request_id', optionLabel: 'description', full: true },
      { key: 'account_infor', label: 'ACCOUNT INFOR' }
    ],
    displayName: (r) => r.account_name || r.account_id,
    children: ['mtr']
  },

  finance: {
    label: 'Finance',
    subtitle: 'Financial overview grouped by Process',
    endpoint: '/table/finance',
    pk: 'id',
    icon: 'bar_chart',
    readOnly: true,
    noActions: true,
    groupBy: ['fy', 'policy_type', 'country'],
    children: [],
    columns: [
      { key: 'id', label: 'ID', hidden: true },
      { key: 'process', label: 'Process', labelKey: 'col.process' },
      { key: 'policy_type', label: 'Process Type', labelKey: 'col.policy_type' },
      { key: 'selling_contract_count', label: 'Selling contract count', labelKey: 'col.selling_contract_count', type: 'number' },
      { key: 'selling', label: 'Selling', labelKey: 'col.selling', type: 'number' },
      { key: 'buying_contract_count', label: 'Buying contract count', labelKey: 'col.buying_contract_count', type: 'number' },
      { key: 'buying', label: 'Buying', labelKey: 'col.buying', type: 'number' },
      { key: 'gm', label: 'GM', labelKey: 'col.gm', type: 'number' },
      { key: 'vat_selling', label: 'Vat Selling', labelKey: 'col.vat_selling', type: 'number' },
      { key: 'selling_wo_vat', label: 'Selling wo VAT', labelKey: 'col.selling_wo_vat', type: 'number' },
      { key: 'vat_buying', label: 'Vat Buying', labelKey: 'col.vat_buying', type: 'number' },
      { key: 'buying_wo_vat', label: 'Buying wo VAT', labelKey: 'col.buying_wo_vat', type: 'number' },
      { key: 'gm_wo_vat', label: 'GM wo VAT', labelKey: 'col.gm_wo_vat', type: 'number' },
      { key: 'incoming_pm_count', label: 'Incoming PM count', labelKey: 'col.incoming_pm_count', type: 'number' },
      { key: 'incoming_payment', label: 'Incoming payment', labelKey: 'col.incoming_payment', type: 'number' },
      { key: 'incoming_payment_paid', label: 'Incoming payment Paid', labelKey: 'col.incoming_payment_paid', type: 'number' },
      { key: 'incoming_pm_not_due_yet', label: 'Incoming PM_Not due yet', labelKey: 'col.incoming_pm_not_due_yet', type: 'number' },
      { key: 'incoming_pm_pending_pm', label: 'Incoming PM_Pending PM', labelKey: 'col.incoming_pm_pending_pm', type: 'number' },
      { key: 'outgoing_pm_count', label: 'Outgoing PM count', labelKey: 'col.outgoing_pm_count', type: 'number' },
      { key: 'outgoing_payment', label: 'Outgoing payment', labelKey: 'col.outgoing_payment', type: 'number' },
      { key: 'outgoing_payment_paid', label: 'Outgoing payment Paid', labelKey: 'col.outgoing_payment_paid', type: 'number' },
      { key: 'outgoing_pm_not_due_yet', label: 'Outgoing PM_Not due yet', labelKey: 'col.outgoing_pm_not_due_yet', type: 'number' },
      { key: 'outgoing_pm_pending_pm', label: 'Outgoing PM_Pending PM', labelKey: 'col.outgoing_pm_pending_pm', type: 'number' },
      { key: 'selling_invoice_count', label: 'Selling invoice count', labelKey: 'col.selling_invoice_count', type: 'number' },
      { key: 'selling_invoice_total_value', label: 'Selling invoice total value', labelKey: 'col.selling_invoice_total_value', type: 'number' },
      { key: 'buying_invoice_count', label: 'Buying invoice count', labelKey: 'col.buying_invoice_count', type: 'number' },
      { key: 'buying_invoice_total_value', label: 'Buying invoice total value', labelKey: 'col.buying_invoice_total_value', type: 'number' },
      { key: 'expense', label: 'Expense', labelKey: 'col.finance_expense', type: 'number' },
      { key: 'non_expense', label: 'Non Expense', labelKey: 'col.non_expense', type: 'number' },
      { key: 'asset', label: 'Asset', labelKey: 'col.finance_asset', type: 'number' },
      { key: 'fy', label: 'FY', labelKey: 'col.finance_fy' },
      { key: 'country', label: 'Country', labelKey: 'col.country', hidden: true }
    ],
    fields: [
      { key: 'id', label: 'ID', type: 'text', disabled: true },
      { key: 'process', label: 'PROCESS', type: 'text', disabled: true },
      { key: 'gm', label: 'GM', type: 'number', disabled: true },
      { key: 'selling', label: 'SELLING', type: 'number', disabled: true },
      { key: 'buying', label: 'BUYING', type: 'number', disabled: true },
      { key: 'expense', label: 'EXPENSE', type: 'number', disabled: true },
      { key: 'asset', label: 'ASSET', type: 'number', disabled: true }
    ],
    detailFields: [
      { section: 'process summary' },
      { key: 'process', label: 'PROCESS', full: true },
      { key: 'policy_type', label: 'PROCESS TYPE' },
      { key: 'fy', label: 'FY' },
      { key: 'gm', label: 'GM', type: 'number' },
      { key: 'gm_wo_vat', label: 'GM wo VAT', type: 'number' },
      { section: 'selling metrics' },
      { key: 'selling_contract_count', label: 'Selling contract count', type: 'number', full: true },
      { key: 'selling', label: 'Selling', type: 'number', full: true },
      { key: 'selling_wo_vat', label: 'Selling wo VAT', type: 'number' },
      { key: 'vat_selling', label: 'Vat Selling', type: 'number' },
      { key: 'incoming_pm_count', label: 'Incoming PM count', type: 'number', full: true },
      { key: 'incoming_payment', label: 'Incoming payment', type: 'number' },
      { key: 'incoming_payment_paid', label: 'Incoming payment Paid', type: 'number' },
      { section: 'buying metrics' },
      { key: 'buying_contract_count', label: 'Buying contract count', type: 'number', full: true },
      { key: 'buying', label: 'Buying', type: 'number', full: true },
      { key: 'buying_wo_vat', label: 'Buying wo VAT', type: 'number' },
      { key: 'vat_buying', label: 'Vat Buying', type: 'number' },
      { key: 'outgoing_pm_count', label: 'Outgoing PM count', type: 'number', full: true },
      { key: 'outgoing_payment', label: 'Outgoing payment', type: 'number' },
      { key: 'outgoing_payment_paid', label: 'Outgoing payment Paid', type: 'number' },
      { section: 'invoices & expenses' },
      { key: 'selling_invoice_count', label: 'Selling invoice count', type: 'number' },
      { key: 'buying_invoice_count', label: 'Buying invoice count', type: 'number' },
      { key: 'selling_invoice_total_value', label: 'Selling invoice total value', type: 'number' },
      { key: 'buying_invoice_total_value', label: 'Buying invoice total value', type: 'number' },
      { key: 'expense', label: 'Expense', type: 'number' },
      { key: 'non_expense', label: 'Non Expense', type: 'number' },
      { key: 'asset', label: 'Asset', type: 'number', full: true }
    ],
    displayName: (r) => `${r.process || r.id} | ${r.fy || ''} | GM: ${r.gm || 0}`,
  }
  });
})();
