version: '3.8'

services:
  # 1. Web App (Node.js)
  app:
    build: .
    container_name: crc_web_app_standalone
    ports:
      - "5221:5221"
    env_file:
      - .env
    restart: always

  # 2. Đường hầm Cloudflare
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: crc_tunnel_standalone
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: always
    depends_on:
      - app

  # 3. Giao diện xem Log (Dozzle)
  dozzle:
    image: amir20/dozzle:latest
    container_name: crc_dozzle_standalone
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

