apiVersion: v1
kind: Secret
metadata:
  name: crc-dev2-env
  namespace: default
stringData:
  DATABASE_URL: "postgres://teraxadmin:TeraX123!%40%23@terax-postgres-service:5432/crcdevdb"
  PORT: "5221"
  JWT_SECRET: "f61b0048e7ecc1456badb69a872b51b6ad2f092041482dd5d19f3c3bafa8e25127aa6416bb88df3d0d44f157496184f195c31450"
  CMS_HMAC_SECRET: "cms_hmac_secret_change_me_2026"
  CMS_BASE_URL: "http://cms-service:5300"
  TENANT_SUBDOMAIN: "dev"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crc-dev2-deployment
  namespace: default
  labels:
    app: crc-dev2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crc-dev2-app
  template:
    metadata:
      labels:
        app: crc-dev2-app
    spec:
      containers:
        - name: crc-dev2-app
          image: terax-ver2-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5221
          envFrom:
            - secretRef:
                name: crc-dev2-env
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: crc-dev2-service
  namespace: default
  labels:
    app: crc-dev2-app
spec:
  type: LoadBalancer
  selector:
    app: crc-dev2-app
  ports:
    - name: http
      port: 5226
      targetPort: 5221
      nodePort: 31412
      protocol: TCP
